# Sample GitLab pipeline YAML for Packer
image:
  name: hashicorp/packer:latest
  entrypoint:
    - '/usr/bin/env'
    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
before_script:
  - packer --version
stages:
  - validate
  - build
  - test
  - deploy
validate:
  stage: validate
  script:
    - find Chapter11/self-hosted -maxdepth 1 -name '*.hcl' -or -name '*.pkr.json' | xargs -I{} packer init {}
    - find Chapter11/self-hosted -maxdepth 1 -name '*.hcl' -or -name '*.pkr.json' | xargs -I{} packer validate {}
build:
  stage: deploy
  environment: production
  script:
    - find Chapter11/self-hosted -maxdepth 1 -name '*.hcl' -or -name '*.pkr.json' | xargs -I{} packer init {}
    - find Chapter11/self-hosted -maxdepth 1 -name '*.hcl' | xargs -I{} packer build {}
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
      
