name: Cloud-Managed
on:
  push:
    branches: [ "main" ]
  paths:
      - Chapter11/cloud-hosted/*
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a multi-line script
        run: |
          pwd
          apt install packer
